parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: symtut
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: bd46b37b15ee468b816a3c8db4f07df7
    database_path: null
